# Generated by Django 5.2.2 on 2025-06-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Author's first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Author's last name", max_length=100),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief biography of the author"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="books_autho_last_na_7ca250_idx",
                    )
                ],
                "unique_together": {("first_name", "last_name")},
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book", max_length=200),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="13-digit ISBN number", max_length=13, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Book description or summary"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Book price in USD", max_digits=10
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of books in stock"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="new",
                        help_text="Physical condition of the book",
                        max_length=10,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(help_text="When the book was published"),
                ),
                ("pages", models.PositiveIntegerField(help_text="Number of pages")),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average rating (0-5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this book is active/visible"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        help_text="Authors of this book",
                        related_name="books",
                        to="books.author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who added this book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Book category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx"),
                    models.Index(
                        fields=["category"], name="books_book_categor_bb0287_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="books_book_created_572b47_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="books_book_is_acti_d03df1_idx"
                    ),
                ],
            },
        ),
    ]
